Ad testing
knative-sandbox/async-component pull request #97
Opened 2021-09-21 20:15 UTC by AngeloDanducci

# Changes

- Add JMeter test plan for performance testing and update README

/kind documentation

Necessary but not sufficient for [this issue](https://github.com/knative-sandbox/async-component/issues/62) so I will avoid auto close with the `Fixes` syntax.

2021-09-22 21:42 UTC, maximilien commented
Please resolve not README conflict

2021-09-22 21:51 UTC, maximilien commented
/ok-to-test

2021-09-22 22:42 UTC, maximilien requested changes
Various feedback. Please address and tag me when ready for another review. Thanks.

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +In order to stress test open the `PerformanceTest.jmx` file with JMeter and edit these properties:
Add a link to the file

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +In order to stress test open the `PerformanceTest.jmx` file with JMeter and edit these properties:
And to JMeter and please specify the version used

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +- In HTTP Request Defaults, edit `Server Name or IP` field to point to your helloworld application.
I suggest including UI screen shots with annotation. And also including CLI commands as alternative. Ideally CLI but if GUI is more intuitive then include both please.

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +    Recall that you can find this by using `kubectl get kservice helloworld-sleep
I think it's more involved then this one `kubectl` command. You likely need to output in JSON and parse that to extract the IP. Search for "Knative Service IP address" and you will find various help on the topic... including kubectl examples.

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +- You may also wish to edit the Graph Results and Summary Report output paths.
Show an example of the graph here

2021-09-22 22:42 UTC, maximilien commented on test/JMeter/README.md
> +The test plan will spin up 100 threads with 10 loops of GET requests to the helloworld application and log the outcome.
Perhaps mention how to change these parameters. I assume changing the JMX file?

2021-09-24 22:51 UTC, maximilien commented
/retest
@AngeloDanducci you need to resolve conflict and push changes again

2021-09-27 19:26 UTC, AngeloDanducci commented
Merge conflict solved, updated information should be good for a re-review.

2021-09-27 21:39 UTC, maximilien approved these changes
/approve
/lgtm

2021-09-27 21:40 UTC, merged